01 maven
VarvaraKrestyanova/java-aqa-training pull request #1
Opened 2021-11-10 18:07 UTC by VarvaraKrestyanova

multi-module maven project structure - 01_maven, 02_git

2021-11-10 20:12 UTC, artemmoroz requested changes

2021-11-10 20:12 UTC, artemmoroz commented on online-store/.idea/.gitignore
> +# Default ignored files
please use gitignore from here https://www.toptal.com/developers/gitignore  or create proper one for java and ide yourself to exculed user specific files.

2021-11-10 20:12 UTC, artemmoroz commented on online-store/.idea/.gitignore
> +# Default ignored files
to apply this changes google apply gitignore on existing repo

2021-11-10 20:12 UTC, artemmoroz commented on online-store/parent/pom.xml
> +    <parent>
online store is alredy a parent, no need to create one more parent module.

2021-11-10 20:12 UTC, artemmoroz commented on online-store/pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
why do you use 1.7 java here, and 1.8 in modules?

2021-11-10 20:12 UTC, artemmoroz commented on online-store/pom.xml
> +    <dependency>
you do not need junit for now.

2021-11-11 14:59 UTC, VarvaraKrestyanova commented on online-store/.idea/.gitignore
> +# Default ignored files
changes are in a new commit

2021-11-11 15:11 UTC, merged